server:
  port: ${PORT:8080}

spring:
  application:
    name: distributed-rate-limiter
  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL:}
      timeout: 5000ms

rate-limiter:
  default-capacity: 10
  default-refill-tokens: 5
  default-refill-period-seconds: 10

logging:
  level:
    com.hbb.ratelimiter: DEBUG

