server:
  port: ${PORT:8080}

spring:
  application:
    name: distributed-rate-limiter
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      username: ${REDIS_USERNAME:}
      ssl:
        enabled: ${REDIS_SSL:false}
      timeout: 5000ms

rate-limiter:
  default-capacity: 10
  default-refill-tokens: 5
  default-refill-period-seconds: 10

logging:
  level:
    com.hbb.ratelimiter: DEBUG

